version: "3"
services:
  todo:
    build: .
    ports:
      - 3030:3030
      - 4040:4040
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todo
      - PORT=3030
    depends_on:
      mysql: 
        condition: service_healthy
    networks:
      - todo
      
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo
networks:
  todo:
volumes:
  mysql_data: