apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-test
spec:
  entrypoint: hello-world
  templates:
    - name: hello-world
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
