
def GIT_ORG_NAME = params.GIT_ORG_NAME
def PROJECT_GIT_REPO = params.PROJECT_GIT_REPO
def BRANCH = 'main'
def GIT_URI = "git@github.com:${GIT_ORG_NAME}/${PROJECT_GIT_REPO}.git"

def AWS_REGION = 'ap-south-1'
def ECR_REPO_URL = "009654692619.dkr.ecr.${AWS_REGION}.amazonaws.com"
def ECR_REPO_NAME = 'versioning-tag'

def ENV = 'stg'
def CHART_REPO_BRANCH = 'main'
def DEPLOY_VALUE_FILE = "k8s_todo.yaml"


pipeline {
  agent any

  tools {
    maven 'Maven 3.9.11'
  }

  stages {
    stage('Clone the Code') {
      steps {
        echo "=================================================="
        echo "Branch: ${BRANCH}"
        echo "ECR Repo: ${ECR_REPO_URL}/${ECR_REPO_NAME}"
        echo "=================================================="

        sshagent(credentials: ['basedynamics']) {
          script {
            sh """
              set -e
              
              # Clean workspace
              rm -rf ${PROJECT_GIT_REPO}_build || true
              mkdir -p ${PROJECT_GIT_REPO}_build
              cd ${PROJECT_GIT_REPO}_build

              # Full clone with all tags
              git clone --branch ${BRANCH} --tags ${GIT_URI}
              cd ${PROJECT_GIT_REPO}

              # Ensure all tags and branches are fetched
              git fetch --all --tags

              echo "Latest commit:"
              git log -1 --pretty=format:"%H - %an - %s (%ci)"
            """
          }
        }
      }
    }

    stage('Generate Version') {
      steps {
        script {
          def version = sh(
            script: """
              cd ${PROJECT_GIT_REPO}_build/${PROJECT_GIT_REPO}
              git fetch --tags
              git describe --tags --abbrev=0 || echo v0.0.0
            """,
            returnStdout: true
          ).trim()

          echo "Last version: ${version}"

          def parts = version.replace("v","").split("\\.")
          def major = parts[0].toInteger()
          def minor = parts[1].toInteger()
          def patch = parts[2].toInteger() + 1

          env.NEW_VERSION = "v${major}.${minor}.${patch}"
          echo "New Version: ${env.NEW_VERSION}"
        }
      }
    }

    stage('Login with ECR') {
      steps {
        script {
          sh """
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO_URL}
          """
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            env.IMAGE_TAG = "${ECR_REPO_URL}/${ECR_REPO_NAME}:${env.NEW_VERSION}"
            
            sh """
              docker buildx create --use || true
              docker buildx inspect --bootstrap
              docker buildx build \
                --platform linux/amd64 \
                -t ${IMAGE_TAG} \
                -f ${WORKSPACE}/${PROJECT_GIT_REPO}_build/${PROJECT_GIT_REPO}/Dockerfile \
                ${WORKSPACE}/${PROJECT_GIT_REPO}_build/${PROJECT_GIT_REPO} \
                --push
            """
            // echo "Docker Image: ${IMAGE_TAG}"

            // image.push()
            // echo image.id
            // docker rmi ${image.id}
            sh """
              cd ${WORKSPACE}/${PROJECT_GIT_REPO}_build/${PROJECT_GIT_REPO}

              sed -i "s|^\\(\\s*tag:\\s*\\).*|\\1${IMAGE_TAG}|" "${DEPLOY_VALUE_FILE}"

              git add "${DEPLOY_VALUE_FILE}"
              git commit -m "Latest Docker Image Tag Update: ${IMAGE_TAG}"
              git push origin ${BRANCH}
            """
          }
        }
      }
    }

    stage('Tag Git Repo') {
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            sh """
              cd ${WORKSPACE}/${PROJECT_GIT_REPO}_build/${PROJECT_GIT_REPO}
              
              # Check if tag already exists
              if git rev-parse "${NEW_VERSION}" >/dev/null 2>&1; then
                echo "Tag ${NEW_VERSION} already exists, skipping"
              else
                git tag ${NEW_VERSION}
                git push origin ${NEW_VERSION}
              fi
            """
          }
        }
      }
    }
  } 
}
