apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.todoApp.name }}
  name: {{ .Values.todoApp.name }}
spec:
  replicas: {{ .Values.todoApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.todoApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.todoApp.name }}
    spec:
      containers:
      - image: {{ .Values.todoApp.image }}
        name: {{ .Values.todoApp.name }}
        env:
        - name: API_URL
          value: {{ .Values.todoApp.env.API_URL }}
        - name: MYSQL_HOST
          value: {{ .Values.mysql.host }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }} 
        ports:
        - containerPort: {{ .Values.todoApp.service.port }} 
