apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  clusterIP: "None"
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - name: {{ .Values.mysql.name }}
      port: {{ .Values.mysql.service.port }}
