apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  serviceName: "mysql"
  replicas: {{ .Values.mysql.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
          name: {{ .Values.mysql.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }} 
