apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.todoApp.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:  {{ .Values.todoApp.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.todoApp.name }}
            port:
              number: {{ .Values.todoApp.service.port }}
